apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoken
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spoken.intern.dev.nav.no
  liveness:
    path: /isalive
    initialDelay: 10
  readiness:
    path: /isready
    initialDelay: 10
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 400
  prometheus:
    enabled: false
    path: /metrics
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      tenant: nav.no
      enabled: true
      claims:
        groups:
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
      allowAllUsers: false
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:sykepenger:fellesordningenforafp.read"
        - name: "nav:sykepenger:avtalefestetpensjon.read"
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
